server:
  port: 8085
  
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.bce.dto
                
  application:
    name: product-query-service
  output:
    ansi:
      enabled: always

  jpa:
     hibernate:
        ddl-auto: update
     show-sql: true   
     properties:
       hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
      url: jdbc:mysql://localhost:3306/product
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"


management:
  endpoints:
     web:
       exposure: 
         include: beans,env,health,info,metrics,mappings
  endpoint:
   health:
     show-details: always
     probes:
        enabled: true
        
# Specify the path of the OpenAPI documentation
springdoc:
 api-docs.path: /api-docs
 swagger-ui.path: /swagger-ui.html
 swagger-ui.enabled: true        