server:
  port: 8086


spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer:  org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: order-command-service
  output:
    ansi:
      enabled: always

  jpa:
     hibernate:
        ddl-auto: update
     show-sql: true   
     properties:
       hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
      url: jdbc:mysql://localhost:3306/product
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver


#management:
#  endpoints:
#     web:
#       exposure: 
#         include: beans,env,health,info,metrics,mappings,prometheus
#  endpoint:
#   health:
#     show-details: always
#     probes:
#        enabled: true